### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by semzor** [nuxeo-sandbox/nuxeo-onlyoffice#1]
Hello, after building with maven there are 3 files:

nuxeo-nxr-server-10.10.zip
nuxeo-onlyoffice-package-10.10-SNAPSHOT.zip
nxr-10.10-SNAPSHOT.zip

do I have to install all?

I am using nuxeo 10.10. nuxeo-onlyoffice-package-10.10-SNAPSHOT.zip package install fine but I couldn't install the other two:

```
~/nuxeo-onlyoffice/nuxeo-onlyoffice-package/target$ sudo nuxeoctl mp-install nuxeo-nxr-server-10.10.zip
Nuxeo home:          /var/lib/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /var/lib/nuxeo/server/templates/common-base
Include template: /var/lib/nuxeo/server/templates/common
Include template: /var/lib/nuxeo/server/templates/postgresql
Include template: /var/lib/nuxeo/server/templates/onlyoffice-integration
Cannot execute command. entry
java.lang.NullPointerException: entry
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:361) ~[?:1.8.0_191]
        at org.nuxeo.connect.update.standalone.StandaloneUpdateService.loadPackageFromZip(StandaloneUpdateService.java:260) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.getLocalPackageFileId(ConnectBroker.java:345) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.checkLocalPackagesAndAddLocalFiles(ConnectBroker.java:1519) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.pkgRequest(ConnectBroker.java:1308) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.pkgRequest(ConnectBroker.java:1278) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.pkgRequest(NuxeoLauncher.java:2796) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.launch(NuxeoLauncher.java:1219) ~[nuxeo-launcher-16924.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.main(NuxeoLauncher.java:1113) [nuxeo-launcher-16924.jar:?]
```
and
```
~/nuxeo-onlyoffice/nuxeo-onlyoffice-package/target$ sudo nuxeoctl mp-install nxr-10.10-SNAPSHOT.zip
Nuxeo home:          /var/lib/nuxeo/server
Nuxeo configuration: /etc/nuxeo/nuxeo.conf
Include template: /var/lib/nuxeo/server/templates/common-base
Include template: /var/lib/nuxeo/server/templates/common
Include template: /var/lib/nuxeo/server/templates/postgresql
Include template: /var/lib/nuxeo/server/templates/onlyoffice-integration
Cannot execute command. entry
java.lang.NullPointerException: entry
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:361) ~[?:1.8.0_191]
        at org.nuxeo.connect.update.standalone.StandaloneUpdateService.loadPackageFromZip(StandaloneUpdateService.java:260) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.getLocalPackageFileId(ConnectBroker.java:345) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.checkLocalPackagesAndAddLocalFiles(ConnectBroker.java:1519) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.pkgRequest(ConnectBroker.java:1308) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.connect.ConnectBroker.pkgRequest(ConnectBroker.java:1278) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.pkgRequest(NuxeoLauncher.java:2796) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.launch(NuxeoLauncher.java:1219) ~[nuxeo-launcher-2288.jar:?]
        at org.nuxeo.launcher.NuxeoLauncher.main(NuxeoLauncher.java:1113) [nuxeo-launcher-2288.jar:?]
```

**Comment by dbnuxeo** [comment]
Hi semzor - the nuxeo package is built as: nuxeo-onlyoffice-package-10.10-SNAPSHOT.zip
You should only install this item.
